<a href="https://colab.research.google.com/github/shikhar11x/Churn_Analysis/blob/main/churn_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

## 1.  ***IMPORTING DATABASE***

In [2]:
conn = sqlite3.connect('customer_churn.db')

sql_query="""
            SELECT name
            FROM sqlite_master
            WHERE type='table'
"""

tables=pd.read_sql(sql_query,conn)

# create dataframe for each table

for table_name in tables['name']:
    df=pd.read_sql(f"SELECT * FROM {table_name}",conn)
    globals()[f"df_{table_name}"]=df
    print(f"Created dataframes: df_{table_name}")

conn.close()

Created dataframes: df_db_customer
Created dataframes: df_db_subscription
Created dataframes: df_db_support

In [3]:
# print tables name and column names
conn=sqlite3.connect('customer_churn.db')
for table_name in tables['name']:
  print(f"\nTable: {table_name}")

  # Get column information
  columns_query=f"PRAGMA table_info({table_name});"
  columns=pd.read_sql(columns_query,conn)
  print("Columns:")
  print(columns['name'].tolist())

conn.close()

Table: db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

Table: db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

Table: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

## 2. ***DATA CLEANING***

In [ ]:
# 1st table df_db_customer

In [8]:
# df_db_customer.head()
df_db_customer.tail()

,customerid,name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [6]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [ ]:
# ---- GOALS ----
# a. rename columne name
# b. drop columns - intest and pincode
# c. change datatype of dob
# d. Data standardization in gender
# e. fix missing values in country

In [12]:
# Rename
df_db_customer.rename(columns={'name' : 'customer_name'},inplace=True)
df_db_customer

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,None,Delhi,Women,1988-12-10 00:00:00,None,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,None,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,None,None
8,0015-UOCOJ,maya,None,Kathmandu,Women,1985-07-07 00:00:00,None,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,None,None
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00,None,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,None,None
12,0018-NYROU,chitra,None,Telangana,Female,2004-12-01 00:00:00,None,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,None,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,None,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [ ]:
# Drop tables

# df_db_customer.drop(df_db_customer.columns[-2:],axis=1)

df_db_customer.drop(columns=['interests','pincode'],inplace=True)

In [26]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     object
 1   customer_name  21 non-null     object
 2   country        18 non-null     object
 3   state          21 non-null     object
 4   gender         21 non-null     object
 5   dob            21 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.1+ KB

In [27]:
# change data type of DOB

df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [29]:
# Data Standardization of gender
df_db_customer['gender'].unique()

array(['Male', 'Female', 'Women', 'Men'], dtype=object)

In [32]:
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [33]:
df_db_customer['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [35]:
# fix missing value
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01

In [39]:
df_db_customer[['country','state']]

   country          state
0    India    Maharashtra
1    India      Karnataka
2    India          Delhi
3    India       Nagaland
4    India          Delhi
5     None          Delhi
6    India      Meghalaya
7    India      Rajasthan
8     None      Kathmandu
9    Nepal      Kathmandu
10   India    Maharashtra
11   India      Karnataka
12    None      Telangana
13   India      Meghalaya
14   India  Uttar Pradesh
15   India          Delhi
16   India      Meghalaya
17   India      Rajasthan
18   India      Telangana
19   India  Uttar Pradesh
20   India    Maharashtra

In [44]:
state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [45]:
df_db_customer[df_db_customer['country'].isna()]

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob]
Index: []

In [ ]:
# 2nd table df_db_subscription

In [46]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,None,None,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,None,None,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,None,None,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [47]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 1.9+ KB

In [51]:
date_col =['subscription_start_date','renewal_date',"cancellation_date"]
df_db_subscription[date_col]= df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

In [ ]:
# 3rd table

In [52]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,None
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,None

In [53]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      object
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [56]:
df_db_support.drop(columns=['col_1','comment'],inplace=True)

In [57]:
df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])

In [58]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      datetime64[ns]
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 420.0+ bytes

DATA CLEANING DONE ✅

### ***FEATURE ENGINEERING AND DATA ANALYSIS***

Creating a new column for churn flag to identify customers who have churned.

In [63]:
df_db_subscription['churn_flag']=np.where(df_db_subscription['cancellation_date'].notna(),1,0)

In [64]:

df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [92]:
df_db_subscription.shape

(21, 12)

In [74]:
df_db_subscription['customerid'].nunique()

21

In [76]:
df_db_customer['customerid'].nunique()

21

In [79]:
df_db_support['customerid'].nunique()

7

In [81]:
df_db_support['customerid'].size

9

In [82]:
df_db_support

   customerid complaint_date escalations  csat_score
0  0003-MKNFE     2024-08-28           N          60
1  0003-MKNFE     2024-08-28           Y          10
2  0013-EXCHZ     2024-01-20           Y          20
3  0013-MHZWF     2025-03-18           N          90
4  0013-SMEOE     2024-11-01           N          30
5  0017-IUDMW     2024-04-10           Y          25
6  0019-EFAEP     2024-09-27           Y          30
7  0022-TCJCI     2024-09-13           Y          10
8  0022-TCJCI     2024-09-14           N          90

In [85]:
df_db_support['complaint_count']=df_db_support.groupby('customerid')['customerid'].transform('count')

In [86]:
df_db_support

   customerid complaint_date escalations  csat_score  complaint_count
0  0003-MKNFE     2024-08-28           N          60                2
1  0003-MKNFE     2024-08-28           Y          10                2
2  0013-EXCHZ     2024-01-20           Y          20                1
3  0013-MHZWF     2025-03-18           N          90                1
4  0013-SMEOE     2024-11-01           N          30                1
5  0017-IUDMW     2024-04-10           Y          25                1
6  0019-EFAEP     2024-09-27           Y          30                1
7  0022-TCJCI     2024-09-13           Y          10                2
8  0022-TCJCI     2024-09-14           N          90                2

In [88]:
df_db_support=df_db_support.sort_values('complaint_date').drop_duplicates("customerid",keep='last')

In [90]:
df_db_support.shape

(7, 5)

In [91]:
# merging tables
df= (df_db_subscription
              .merge(df_db_customer, on='customerid',how='left')
              .merge(df_db_support, on='customerid',how='left')

 )

In [93]:
df.shape

(21, 21)

In [94]:
df.to_csv('exported_churn_data.csv',index=False)

## ***DATA ANALYSIS***

1.  churn Rate

In [122]:
df.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'complaint_date', 'escalations', 'csat_score', 'complaint_count',
       'tenure_days'],
      dtype='object')

In [123]:
churn_rate=df['churn_flag'].mean()*100
print('Churn rate = ',round(churn_rate,2),'%')

Churn rate =  28.57 %

2. Retension Rate

In [124]:
retension_rate=100-churn_rate
print('Retension rate = ',round(retension_rate,2),'%')

Retension rate =  71.43 %

3. Churn by Plan Type

In [125]:
churn_by_plan=(df.groupby('plan_type')['churn_flag'].mean().mul(100).round(2)
.reset_index(name='churn_rate_pct'))

print(churn_by_plan)

  plan_type  churn_rate_pct
0     Basic           60.00
1   Premium           14.29
2  Standard           22.22

4. Avg Revenue per user - ARPU

In [126]:
arpu=df['monthly_charges'].mean()
print("ARPU = ",round(arpu,2),"₹")

ARPU =  18.85 ₹

5. Avg tenure

In [127]:
today=pd.Timestamp.today()

df['tenure_days']=np.where(
    df['cancellation_date'].notna(),
     (df['cancellation_date']-df['subscription_start_date']).dt.days,
    (today-df['subscription_start_date']).dt.days
)
avg_tenure =df['tenure_days'].mean()
print("Avg tenure = ",avg_tenure)

Avg tenure =  1488.0

6. Revenue loss at risk

In [128]:
revenue_at_risk=df.loc[df['churn_flag']==1,'monthly_charges'].sum()
print("Revenue At risk =",revenue_at_risk)

Revenue At risk = 73.94

7. Esclation **Rate**

In [132]:
escalations_rate =(df['escalations']== 'Y').mean()*100
print("Escalations Rate = ",round(escalations_rate,2))

Escalations Rate =  19.05

8. Avg complaint Rate

In [136]:
avg_complaints=df['complaint_count'].sum() /df['customerid'].nunique()

print("Avg Complaint rate =",round(avg_complaints,2))

Avg Complaint rate = 0.43

9. Correlation Esclation vs churn

In [139]:
df['escalations']=np.where(df['escalations']=='Y',1,0)  #ecoding string to int

In [141]:
corr_df=df[['escalations','churn_flag']].dropna()

correlation=corr_df['escalations'].corr(df['churn_flag'])
print("Correlation between escalations and churn = ",round(correlation,2))

Correlation between escalations and churn =  0.77

10. Churn Risk